version: '1.0'
services:
  app:
    platform: linux/amd64
    image: 'dnzyslrmk/loto:latest'
    ports:
      - "80:9000"
    environment:
      MONGO_URI: ${MONGO_URI} 
      PORT: ${PORT} 
      API_VERSION: ${API_VERSION} 
      JWT_SECRET: ${JWT_SECRET} 
      RESEND_API_KEY: ${RESEND_API_KEY} 
      GMAIL_CLIENT_ID: ${GMAIL_CLIENT_ID} 
      GMAIL_CLIENT_SECRET: ${GMAIL_CLIENT_SECRET} 
      GMAIL_REDIRECT_URI: ${GMAIL_REDIRECT_URI} 
      GMAIL_ACCESS_TOKEN: ${GMAIL_ACCESS_TOKEN} 
      GMAIL_REFRESH_TOKEN: ${GMAIL_REFRESH_TOKEN} 
      GMAIL_TYPE_TOKEN: ${GMAIL_TYPE_TOKEN} 
      GMAIL_SCOPE_TOKEN: ${GMAIL_SCOPE_TOKEN} 
      GMAIL_EXPIRE_TOKEN: ${GMAIL_EXPIRE_TOKEN} 
      WELL_KNOWN_URL: ${WELL_KNOWN_URL}
      WELL_KNOWN_CONTENT: ${WELL_KNOWN_CONTENT}
      NODE_ENV: ${NODE_ENV}
    volumes:
      sharedVolume:
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: '/home/ubuntu/sharedVolume'