version: '1.0'
services:
  app:
    platform: linux/amd64
    image: 'dnzyslrmk/loto:latest'
    ports:
      - "80:9000"
    environment:
      MONGO_URI: ${MONGO_URI} 
      PORT: ${PORT} 
      API_VERSION: ${API_VERSION} 
      JWT_SECRET: ${JWT_SECRET} 
      WELL_KNOWN_URL: ${WELL_KNOWN_URL}
      WELL_KNOWN_CONTENT: ${WELL_KNOWN_CONTENT}
      NODE_ENV: ${NODE_ENV}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
    volumes:
      - ./ssl:/root/securiry/ssl